### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by gowrav** [WebReflection/benja#10]
Support for 
> Odroid C2
> Nano Pi K2

**Comment by WebReflection** [comment]
The problem is Electron, AFAIK not built for ARM64 yet, otherwise it'd be there already

**Comment by gowrav** [comment]
Thanks... lets keep this open for a resolve..

**Comment by WebReflection** [comment]
Nothing I can resolve here though.

**Comment by zeke** [comment]
👋 I'm on the Electron team. We are hoping to have an ARM64 build soon. I will try to remember to report back here when we do.

**Comment by WebReflection** [comment]
@zeke did you forget to report? :smiley: 

just asking for a possible ETA so I can either close or wait and publish a new ISO for Pi3, thanks

**Comment by zeke** [comment]
> did you forget to report?

Didn't forget. It just doesn't exist yet.

**Comment by WebReflection** [comment]
OK, closing for maintenance sake but please do notify me/us/here if there's any progress, thank you!
