### ISSUE TITLE
Raspberry Pi 2 System Update fails whole benja startup

### ISSUE THREAD

**Issue by TheAifam5** [WebReflection/benja#13]
Hey,
Yesterday i used official ISO from benja.io and I tried to update the system.
Package manager asking is about mesa package that is replaced by other package.
So i successfully upgraded system but after the restart doesn't work anymore.
I tried also install everything manually but i seen in logs that electron can't start with xinit.

Also i will provide more information tomorrow.

Would be lovely if you will upgrade ISO for Raspbery Pi 2 <3

Regards TheAifam5

**Comment by WebReflection** [comment]
are you sure you tested the latest ISO? I have changed it to use Xorg and native VC4 mesa instead of the old weston-pi blob based distro, maybe you should try to re-download the current ISO for Pi 2/3 and try to update that one instead of the old one.

If that's what you've done already, I'll have a look, thanks.

**Comment by TheAifam5** [comment]
Hey,

So i lost like 8hrs of my day to figure out what exactly makes my issue.

After full update Xorg doesn't work with official Raspberry Pi Touchscreen 7" but via HDMI works. I found that the package "linux-firmware" makes problems, exactly "vc4-kms-v3d". After changing to the experimental version "vc4-fkms-v3d" touchscreen works.

with "vc4-kms-v3d" Xorg see the official RPi Touchscreen but doesnt show anything and Xorg logs doesn't contains any error and Electron app works in background, so everything works doesnt show up on the screen, on HDMI shows. So i found that they released experimetal "vc4-fkms-v3d" and works perfectly.

Also i seen that resolution is 2px smaller 799x479 (should be 800x480).

Looks like upstream issue.

**Comment by WebReflection** [comment]
gosh, thanks for investigating. what do you think I should do? I'd rather stick with mainstream but this is bad

**Comment by TheAifam5** [comment]
So i will report that to the mainstream rpi2 firmware repo and if that is a bug on their side, u can apply small patch like i wrote before (just change "vc4-kms-v3d" to "vc4-**f**kms-v3d"). Don't forget to test it :) Because i made a lot of changes, tries, reboots, reinstalls etc and i remember that problem was exactly with dtoverlay.

**Comment by WebReflection** [comment]
did 4.9 work ?

**Comment by WebReflection** [comment]
FYI I've fully updated the Raspberry Pi 2/3 iso. It now uses Weston 2, vc4-fkms-v3d (works with both HDMI and RPi Display), node 8.X and npm 5.x + Electron 1.6.x
