### ISSUE TITLE
Support for PocketC.H.I.P./C.H.I.P.

### ISSUE THREAD

**Issue by gabrielperales** [WebReflection/benja#14]
I think it would be nice to have Benja running on a pocketC.H.I.P. Maybe it could be easy to support it because pcDuino also run over an AllWinner cpu.

**Comment by WebReflection** [comment]
I have a pocketC.H.I.P and it's cool ... but also, it's not officially supported by ArchLinux for ARM.
https://archlinuxarm.org/platforms

Nothing I can do here, sorry.
