### ISSUE TITLE
Raspberry Pi Zero (W) support?

### ISSUE THREAD

**Issue by zeke** [WebReflection/benja#15]
Hi @WebReflection! Do you know if benja can be installed on a Zero?

**Comment by WebReflection** [comment]
well, it's again a matter of Electron builds. ArchLinux and VideoCore 4 works pretty well there:
https://www.youtube.com/watch?v=hCLhGqadv04

TL;DR Gtk+ and WebKitGTK+ works like a charm there but the architecture is not ARMv7 but ARMv6 (or ARMv11) meaning current Electron ARM builds won't work and to be honest, if I remember correctly, there's no way to build Chromium on Raspberry Pi 1 or Pi 0 (same CPU) so I am not sure you want to go down that path but it'd be awesome!

**Comment by zeke** [comment]
> there's no way to build Chromium on Raspberry Pi 1 or Pi 0

Do you know why that is?

**Comment by WebReflection** [comment]
I told you, different ARM architecture.

However, at some point Googlers said they would have brought Chromium to Pi 1/0 but that was long time ago and afaik nothing happened

**Comment by WebReflection** [comment]
Nothing happened here, closing for maintenance sake.
