### ISSUE TITLE
Tools to format / flash the SD-Card easily

### ISSUE THREAD

**Issue by maertz** [WebReflection/benja#19]
Hi there, first of all - thanks for sharing this awesome project!
I've had huge issues formatting and flashing my SD-Card through the terminal.

Here two tools which makes the life a lot easier ( at least for me on OSX ).
Formatting the SD-Card: https://www.sdcard.org/downloads/formatter_4/
Flashing the SD-Card: https://etcher.io/

Just wanted to share that :)

**Comment by WebReflection** [comment]
I don't find `dd if=iso of=sdcard` too hostile but for the quick look I had I like etcher.

Maybe you can help filing a PR to the documentation ? :wink:
