### ISSUE TITLE
Papirus install instructions

### ISSUE THREAD

**Issue by maertz** [WebReflection/benja#20]
I'm having an issue with these papirus instructions.
https://github.com/WebReflection/benja/tree/gh-pages/examples/papirus

**1**
```
# install dependencies
sudo pacman -Syu --needed --noconfirm python-imaging fuse bc git i2c-tools ttf-freefont ntp
```
```
error: failed to commit transaction (conflicting files)
ca-certificates-utils: /etc/ssl/certs/ca-certificates.crt exists in filesystem
```

**2**
```
# use the Papirus installer, ignore apt-get warnings
curl -sSL https://goo.gl/i1Imel | sudo bash
```
```
bash: line 4: apt-get: command not found
bash: line 5: apt-get: command not found
bash: line 6: apt-get: command not found
bash: line 7: apt-get: command not found
bash: line 10: raspi-config: command not found
bash: line 11: raspi-config: command not found
```

**Comment by WebReflection** [comment]
this is archlinux, no debian or ubuntu.

the issue you are having seems to be relatewd to this one:
https://www.archlinux.org/news/ca-certificates-utils-20170307-1-upgrade-requires-manual-intervention/

I need to either update the image or the documentation.

Thanks.

**Comment by maertz** [comment]
> this is archlinux, no debian or ubuntu.

I guess that was related to "apt-get", sure was just mentioning because the link in following line contains apt-get commands.

`curl -sSL https://goo.gl/i1Imel | sudo bash`

Thanks for the quick response, i'll try the work around to update at least the os - thanks for pointing it out.

**Comment by WebReflection** [comment]
if it's about warnings, it says: _use the Papirus installer, **ignore apt-get warnings**_
I believe I've written that for a reason

About the rest, please try to solve one thing per time. Update all the things after solving the credentials issue, then we'll see the rest :wink:

**Comment by maertz** [comment]
Sorry was so excited - had to run all at the same time :D
