### ISSUE TITLE
[Suggestion] `BENJA` environment variable

### ISSUE THREAD

**Issue by niklashigi** [WebReflection/benja#30]
It would be great if Benja would always set a specific environment variable to true, maybe `BENJA` or `BENJA_OS`. This would allow developers to easily check whether their application is currently running on a Benja device, like this:
```javascript
if(process.env.BENJA)
  console.log("I'm on a Benja device! :D")
else
  console.log("I'm on a normal computer. :I")
```
[Travis CI](https://travis-ci.org/) offers [a similar variable called `TRAVIS`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) that indicates that a program is run by a Travis build.

**Comment by WebReflection** [comment]
```js
if (/^x\d+/.test(process.arch)) {
  console.log("I'm on a normal computer. :I");
} else {
  console.log("I'm on a Benja device! :D");
}
```

**Comment by niklashigi** [comment]
@WebReflection Thanks for the quick answer!

**Comment by WebReflection** [comment]
sorry I rushed, but re-creating 12 ISO of 8 GB each to put some info you could discover otherwise is not my highest priority now.

However, you're totally right, there should be some unique env variable to check against.

That's the best way to go, but not these days. Apologies.

**Comment by WebReflection** [comment]
P.S. will be in, next deploy!
