### ISSUE TITLE
VFAT filesystem for /home/benja/app prevents using app.makeSingleInstance()

### ISSUE THREAD

**Issue by rhclayto** [WebReflection/benja#32]
Since `/home/benja/app` is formatted as VFAT, which cannot use symlinks, it is impossible to use BENJA with Electron's `app.makeSingleInstance()` method, which depends on creating symlinks in the app directory. Formatting as ext4 makes it possible to use this method. See https://github.com/electron/electron/issues/10349 .

**Comment by rhclayto** [comment]
Another solution: change the TMPDIR environment variable in the main electron process to somewhere outside the app directory: 

```js
process.env['TMPDIR'] = '/tmp';
```

**Comment by WebReflection** [comment]
awesome, so all you need to do is to change the package.json inside the VFAT folder to set such env variable upfront, right?

```
  "scripts": {
    "start": "TMPDIR=/tmp electron index.js"
  }, 
```

**Comment by rhclayto** [comment]
Works for me!

**Comment by rhclayto** [comment]
You might want to add this information to the documentation.
