### ISSUE TITLE
Unable to use in VMWare Fusion EFI

### ISSUE THREAD

**Issue by t3rminus** [WebReflection/benja#34]
Trying to install this in VMWare Fusion, I get the following error on boot:
`Not a Secure Boot Platform 14`

VMWare Fusion does not support secure boot at all, so there is nothing to enable/disable that I am aware of. Any ideas?

**Comment by WebReflection** [comment]
Hi, this project has very specific target **Hardware** platforms. Is your SBC listed anywhere in here?

**Comment by t3rminus** [comment]
Yes, although I'd prefer to work in a virtual environment for dev (so I don't have to cart around my SBC/Display), and I was following the from-scratch X86/AMD64 instructions: https://benja.io/docs/#how-to-install-b-e-n-j-a-environment-from-the-scratch-i686-x86_64

**Comment by WebReflection** [comment]
those instructions are for SBC with either X86 (Winnowboard Max) OR AMD64 (Gizmo2) SBCs.

It makes nearly zero sense to support virtual environments since you can already develop whatever you want on your actual PC/Mac just after burning the SDCard and using it directly on your PC/Mac.

Apologies but this project is not sustainable and I'm not planning to waste time on virtual envs as target, these have never been useful so far.

**Comment by t3rminus** [comment]
I'm sorry you feel that way. I, personally, find virtual environments to be extremely useful for compartmentalizing project development and providing a better understanding of the final target environment.

I'm also sorry to hear you're not finding this project sustainable. I think it's brilliant, and will try and help in any way I can.

**Comment by WebReflection** [comment]
![screenshot from 2017-09-22 22-21-52](https://user-images.githubusercontent.com/85749/30764786-7657110e-9fe4-11e7-8818-1e5765c3867a.png)

this project has never raised any concrete interest in the last 3 years ... that button, nobody clicks it. 

I am not actively making changes, I just maintain most used parts and what's really needed.

Everything else is a waste of time I don't have at this moment.

**Comment by WebReflection** [comment]
PRs welcome, of course. Sorry, I don't mean to be rude, I just really have 9876543456789 projects going on and Benja is just fine the way it is for 99% of use cases.

**Comment by WebReflection** [comment]
P.S. .... also, secure boot can be disabled or not used at all. Disabling it might be it

**Comment by t3rminus** [comment]
Haha. No worries! I think a lot of us have 9876543456789 projects going. Sometimes they overlap and great OSS collaboration happens. If I have any "overlap" time, and I get this working, I'll make a PR.

As for secure boot: VMWare doesn't even have or support it. So there's nothing I can disable. Still a few things to try on my own though. Thanks so much for your quick replies.

**Comment by WebReflection** [comment]
> VMWare doesn't even have or support it.

it doesn't know what it is and it complains about it? How weird.

here the thing: secure boot is just EFI partition (basic FAT32) with efibootmanager ... there are flags to disable EFI boot (maybe) or probably should be added ... Gizmo2 doesn't use UEFI so maybe you wan t to try that as target platform.
