### ISSUE TITLE
Setting Hostname & Correct Time

### ISSUE THREAD

**Issue by rdamron** [WebReflection/benja#36]
Any options to set the hostname via disk? I also need to set the correct date time. Is NTP enabled on Benja?

Any suggestions on where i should get started with this?

**Comment by WebReflection** [comment]
[Set the hostname](https://wiki.archlinux.org/index.php/Network_configuration#Set_the_hostname)
[NTP](https://wiki.archlinux.org/index.php/Network_Time_Protocol_daemon)

you can connect either via SSH or directly through the SBC (rename `package.json` to `package.jsoff` for a one-off boot to shell)
