### ISSUE TITLE
Sometimes doesn't boot

### ISSUE THREAD

**Issue by LicaSterian** [WebReflection/benja#40]
I'm having mixed results booting the app on a rPi3, sometimes it boots just fine, sometimes not at all. I have it connected to a original 7" touch screen. Is this a known issue? Thanks.

**Comment by WebReflection** [comment]
Nothing I’m aware of

**Comment by WebReflection** [comment]
this is not actionable for me. When you'll have a consistent way to reproduce feel free to reopen.
