### ISSUE TITLE
QEMU Emulation

### ISSUE THREAD

**Issue by mrefaie** [WebReflection/benja#43]
Is there any way to emulate BENJA using QEMU?

**Comment by WebReflection** [comment]
you flush benja, you put in your computer, you type `npn install` and `npm start` ... that is the emulator?

**Comment by lahdekorpi** [comment]
@mrefaie I just installed Arch Linux into a virtual machine as usual, and then manually installed Benja following the [instructions](https://benja.io/docs/#how-to-install-b-e-n-j-a-environment-from-the-scratch-i686-x86_64). This is only in the case you want to test the rest of the OS-level stuff, not just the app development as mentioned above.

**Comment by WebReflection** [comment]
To install ArchLinux on a VM this might be handy: https://medium.freecodecamp.org/installing-arch-linux-from-scratch-b595095ddd48

**Comment by WebReflection** [comment]
no answer in months
