### ISSUE TITLE
Launch App on SPI display (Raspberry PI)

### ISSUE THREAD

**Issue by schlangguru** [WebReflection/benja#48]
Hi, i try to launch the application on my 3.2" spi display. The first few lines of the boot commands are shown on the display but the app itself still shows only up on the hdmi output. I'm using the RPI ISO image from the benja homepage.

**Comment by WebReflection** [comment]
I've configured TFT displays through this file:
https://github.com/WebReflection/benja/blob/gh-pages/os/sh/rpi-tft

you need to drop Weston, since unfortunately most display work only on Xorg, and change the startup too.

You should also ask to your display seller how to configure it in Xorg.
