### ISSUE TITLE
Cache update

### ISSUE THREAD

**Issue by alexbenza92** [WebReflection/benja#6]
Hello, i have a problem when i modify index.html the changes aren't appearing on the screen even if i reboot the device. What should i do ? Thank you!

**Comment by WebReflection** [comment]
have you tried cache invalidation?

try to load this url in your `index.js` file

```js
.loadURL('http://localhost:8080/?_=' + Math.random())
```

If that solves, it might be that `tiny-cdn` does its job too greedly, forcing cache a bit too much.

Please let me know, thanks.

**Comment by alexbenza92** [comment]
Solved thank you!

Benza Alexandru

[ I have edited your unnecessary details sent via your email client ]

**Comment by WebReflection** [comment]
that's something puzzling me, tidy-cdn is awesome for prod but painful in development.

Maybe I should disable cache completely through an env flag ... I'll think about it, glad I've sorted your problem.

Bear in mind same thing might be needed for external files you are loading through that page.
