### ISSUE TITLE
Benja as a bootable usb key for mac

### ISSUE THREAD

**Issue by squirelo** [WebReflection/benja#8]
Is there an easy way or a tool to generate a bootable usb key with benja to be used on a mac?

I'm struggling to setup manually the EFI bootloader since few days.

Thanks for your help!

**Comment by WebReflection** [comment]
you don't need Benja OS to run / test / develop Benja compatible Apps, you just need to plugin the USB stick, open the BENJA folder, run `npm install` and then `npm start` in there to see the App.
